#!/bin/bash
# deploy.sh - Deployment helper script

echo "🚀 Attendance Management System - Render Deployment Guide"
echo "========================================================="
echo ""
echo "📁 This repository contains both frontend and backend services"
echo ""
echo "🔧 Backend Service (Flask):"
echo "   - Service Type: Web Service"
echo "   - Runtime: Python 3.11+"
echo "   - Root Directory: backend"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python app.py"
echo ""
echo "🌐 Frontend Service (Next.js):"
echo "   - Service Type: Web Service"
echo "   - Runtime: Node.js 18+"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm start"
echo ""
echo "⚙️  Environment Variables to set in Render dashboard:"
echo ""
echo "Backend:"
echo "   SUPABASE_URL=your_supabase_url"
echo "   SUPABASE_ANON_KEY=your_anon_key"
echo "   SUPABASE_SERVICE_ROLE_KEY=your_service_role_key"
echo "   FLASK_ENV=production"
echo ""
echo "Frontend:"
echo "   NEXT_PUBLIC_API_URL=https://your-backend-service.onrender.com"
echo "   NODE_ENV=production"
echo ""
echo "📋 Deployment Steps:"
echo "1. Create Backend service first"
echo "2. Get backend URL after deployment"
echo "3. Create Frontend service with backend URL"
echo "4. Both services will run independently"
echo ""
echo "✅ Ready for deployment!"